stages:
- name: Build
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: |-
        pwd
        ls -al
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: juixtu/nginx:${CICD_EXECUTION_SEQUENCE}
      registry: harbor.youjiqing.club
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
