stages:
- name: Build
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: |-
        pwd
        ls -al
- name: Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: juixtu/nginx:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34407
timeout: 60
notification: {}
