apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-demo
    from: pipeline
  name: nginx
  namespace: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-demo
  template:
    metadata:
      labels:
        app: pipeline-demo
    spec:
      containers:
      - image: 127.0.0.1:34949/juixtu/rancher:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
