apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: juixtu/rancher:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
